### ISSUE TITLE
YAY! A Javascript Wrapper!

### ISSUE THREAD

**Issue by DeveloperAlly** [only4sim/lilypad-javascript-wrapper#1]
Heya, thanks for the submission! As a prev front end dev, having a js wrapper is SO USEFUL to devs :)

Are you using Lilypad v2 btw? Or v1? 

Do you intend to continue working on this? :)

**Comment by only4sim** [comment]
Hey,

Thanks for the feedback! I'm glad to hear that you find the JS wrapper useful. Developer use is a huge motivator for me. I'm using LilyPad v1 for this project. If there are any significant advantages of v2, I'm also happy to try it.

I will continue working on this project. I want to make it more polished and feature-rich, and I'm also interested in exploring the possibility of making it more accessible to beginners.

P.S. If you have any specific suggestions for how I can improve the project, please let me know. I'm always looking for ways to make it better.
